create database MATCHUP
drop database MATCHUP
use MATCHUP

create table INSCRIPTION (ID_INSCRIPTION INT auto_increment primary key,
ID_USER INT,
ID_TOURNAMENT INT)

select * from INSCRIPTION

CREATE TABLE USERS ( ID_USER INT auto_increment  PRIMARY key,
USERNAME VARCHAR(25),
EMAIL VARCHAR(50),
DATE_REGISTER DATE, 
PASSWORD VARCHAR(20), 
FIRST_NAME VARCHAR(25), 
LAST_NAME VARCHAR(25), 
IMAGE VARCHAR(50),
USER_LEVEL INT );


drop table USERS
insert into USERS values(0, 'Ext4', 'admmin@gmail.com', '2024-12-10','123', 'aaron', 'soto', 'IMG' ,1)
select * from USERS

CREATE TABLE TOURNAMENT (ID_TOURNAMENT int AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30), 
RULESET VARCHAR(20),
ATTENDES INT,
ID_VIDEOGAME INT,
IMAGE VARCHAR(50),
STATUS CHAR(20),
DATE DATE)
drop table TOURNAMENT
SELECT * FROM TOURNAMENT

select TOURNAMENT.NAME, TOURNAMENT.RULESET, TOURNAMENT.STATUS, VIDEOGAME.NAME from TOURNAMENT inner join VIDEOGAME on 
VIDEOGAME.ID_VIDEOGAME=TOURNAMENT.ID_VIDEOGAME
insert into TOURNAMENT values (0,'Holiday Out V1','doble eliminaciont', 25, 3, 'image', 'finalizado', 'date')
insert into TOURNAMENT values (0,'Tech Smash V1','doble eliminacion', 24, 3, 'image', 'finalizado', '1-12-24')
insert into TOURNAMENT values (0,'Road to Neo Smash VI','doble eliminacion', 25, 3, 'image', 'finalizado', '20-09-24')

CREATE TABLE BRACKET (ID_BRACKET INT AUTO_INCREMENT PRIMARY KEY,
ID_TOURNAMENT INT,
ID_USER INT, 
INITIAL_DATE DATE, 
END_DATE DATE,
ID_SET INT,
NAME VARCHAR (3),
PHASE VARCHAR (35))

select * from BRACKET

CREATE TABLE GAME (ID_SET INT auto_increment PRIMARY KEY,
ID_GAME INT, 
ID_USER INT,
RESULT VARCHAR (6)
)

select * from GAME;


CREATE TABLE SET_GAME (ID_GAME INT AUTO_INCREMENT PRIMARY KEY, 
ID_TOURNAMENT INT,
ID_USER INT,
ID_USER2 INT,
GAME_DATE DATE, 
ID_BRACKET INT)

select * from SET_GAME 

CREATE TABLE VIDEOGAME (ID_VIDEOGAME INT PRIMARY KEY,
NAME VARCHAR (30),
PLATAFORM VARCHAR (15),
GENDER VARCHAR (15))



select * from VIDEOGAME

Create Table PAYMENT (ID_PAY INT AUTO_INCREMENT PRIMARY KEY,
ID_TOURNAMENT INT, 
PAY DECIMAL(6), 
COST_VENUE DECIMAL(6), 
ID_USER INT, 
PAY_DATE DATE, 
PAY_METHOD VARCHAR(20), 
TAX_AMOUNT DECIMAL(6),
DISCOUNT DECIMAL (6),
STATUS VARCHAR (20))

select * from PAYMENT

CREATE TABLE CONTROL_TOURNAMENT(ID_TOURNAMENT INT AUTO_INCREMENT PRIMARY KEY,
MENSAJE VARCHAR(30), 
FECHA DATE)


CREATE TRIGGER after_inscription_insert_payment
AFTER INSERT ON INSCRIPTION
FOR EACH ROW
BEGIN
    INSERT INTO PAYMENT (ID_TOURNAMENT, PAY, COST_VENUE, ID_USER, PAY_DATE, PAY_METHOD, TAX_AMOUNT, DISCOUNT, STATUS)
    VALUES (NEW.ID_TOURNAMENT, 50.00, 10.00, NEW.ID_USER, CURDATE(), 'Tarjeta de Crédito', 5.00, 0.00, 'Completado');
END



